### ISSUE TITLE
Broken Links on PyPI Page

### ISSUE THREAD

**Issue by krypto-kiddo** [xeroc/python-solana-actions#3]
The URLs provided for the implementation examples in the "Examples" section on the PyPI page for the `solana-actions` package appear to be broken. The links are intended to direct users to examples using Flask and FastAPI, but they currently lead to non-existent pages.

**Broken Links:**
Using Flask - https://pypi.org/project/solana-actions/examples/flask/
Using FastAPI - https://pypi.org/project/solana-actions/examples/fastapi/

**Steps to Reproduce:**
1. Go to the PyPI page for solana-actions.
2. Scroll down to the "Examples" section.
3. Click on the links labeled "Using Flask" and "Using FastAPI".

![image](https://github.com/user-attachments/assets/b1c38302-df37-4515-a522-549b49e65f99)

The issue seems to be with the URLs provided on the PyPI page. Kindly update the links to direct users to the correct examples.

Thank you for your attention to this matter.

**Comment by xeroc** [comment]
Nice find. Thanks for pointing this out.
Fix is in the pipelines. Pypi should be updated soon
